# Generated by Django 3.2.1 on 2021-05-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='processExecutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_title', models.CharField(help_text='Text Field, 254, Characters.', max_length=254, verbose_name='Process ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Completed At')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed')], help_text='Text Choice Field, 50, Characters.', max_length=50, verbose_name='Execution Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
        ),
    ]
