# Generated by Django 3.2.1 on 2021-05-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_processexecutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='root_category',
        ),
        migrations.AlterModelOptions(
            name='processexecutions',
            options={'verbose_name': 'Execution', 'verbose_name_plural': 'Executions'},
        ),
        migrations.AddField(
            model_name='processexecutions',
            name='node_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Node ID'),
        ),
        migrations.AddField(
            model_name='processexecutions',
            name='node_type',
            field=models.CharField(choices=[('root', 'root'), ('child', 'child')], default='root', max_length=254, verbose_name='Node Type'),
        ),
        migrations.AlterField(
            model_name='processexecutions',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='processexecutions',
            name='process_title',
            field=models.CharField(help_text='Text Field, 254, Characters.', max_length=254, verbose_name='Process Title'),
        ),
        migrations.DeleteModel(
            name='catagory',
        ),
        migrations.DeleteModel(
            name='subCategory',
        ),
    ]
