# Generated by Django 3.2.1 on 2021-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_processexecutions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processexecutions',
            name='node_id',
            field=models.CharField(default='', help_text='Node id of Amazon Category For Marketplace', max_length=254, verbose_name='Node ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processexecutions',
            name='node_type',
            field=models.CharField(choices=[('root', 'root'), ('child', 'child')], default='root', help_text='Select Root is category is Main and select child if node id is sub category of any Category', max_length=254, verbose_name='Node Type'),
        ),
        migrations.AlterField(
            model_name='processexecutions',
            name='process_title',
            field=models.CharField(help_text='Process title only for regonization, Try to use unique name', max_length=254, verbose_name='Process Title'),
        ),
    ]
